services:
  - type: web
    name: cctv-ai-server
    env: python
    # 경로 수정: model_server 폴더 안의 파일들 사용
    buildCommand: pip install -r model_server/requirements.txt
    startCommand: python model_server/main.py
    # 추가 환경 변수로 최적화
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        fromService:
          type: web
          name: cctv-ai-server
          property: port
      # Render 최적화를 위한 추가 환경 변수
      - key: RENDER_MEMORY_LIMIT
        value: "true"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      # Python 버퍼링 비활성화 (로그 실시간 확인용)
      - key: PYTHONUNBUFFERED
        value: "1"